
DSN: "user=postgres dbname=postgres password=changeme sslmode=disable"
GAUTH_CLIENT_ID: "897582808231-9l4h8279j73tk104cvb1rnlp22vemgg3.apps.googleusercontent.com"
GAUTH_CLIENT_SECRET: "FsfJ-vGTHbvtRbw2tEexWaLO"
